apiVersion: v2
name: test-springboot-6
description: Helm chart for test-springboot-6 — Mastercard MCMicroservice
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: group:default/msbx-engineering
keywords:
  - mastercard
  - microservice
  - spring-boot
  - aws
